version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - sharded-mongodb-docker_internalnetwork
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
networks:
  sharded-mongodb-docker_internalnetwork:
    external: true
