version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
    restart: always
    networks:
      - tienda_default
networks:
  tienda_default:
    external: true
